#pragma once

// Default configuration (overridden by mc.ini / CS commands).

#define CFG_DEFAULT_INIT_SPEED_MM_S 50.0f
#define CFG_DEFAULT_INIT_ACCEL_MM_S2 200.0f
#define CFG_DEFAULT_MAX_SPEED_MM_S 100.0f
#define CFG_DEFAULT_MAX_ACCEL_MM_S2 300.0f
#define CFG_DEFAULT_STEPS_PER_MM 320.0f
#define CFG_DEFAULT_SLIDER_MIN_MM 0.0f
#define CFG_DEFAULT_SLIDER_MAX_MM 600.0f
#define CFG_DEFAULT_INIT_VERBOSE 0
#define CFG_DEFAULT_INIT_TERMINAL 0
#define CFG_DEFAULT_INIT_DEBUG_LEVEL 3
#define CFG_DEFAULT_WDT_USE 1

/* Pin active level: 0 = low-active, 1 = high-active */
#define CFG_DEFAULT_DRV_STEP_ACTIVE 1
#define CFG_DEFAULT_DRV_DIR_ACTIVE 1
#define CFG_DEFAULT_DRV_EN_ACTIVE 0
#define CFG_DEFAULT_SW_HOME_ACTIVE 0
#define CFG_DEFAULT_SW_HOME_USE 0
#define CFG_DEFAULT_DRV_ERROR_ACTIVE 0
#define CFG_DEFAULT_SW_LIMIT_L_ACTIVE 0
#define CFG_DEFAULT_SW_LIMIT_R_ACTIVE 0
#define CFG_DEFAULT_SW_LIMIT_L_USE 0
#define CFG_DEFAULT_SW_LIMIT_R_USE 0
#define CFG_DEFAULT_EXT_ACTIVE 1 /* EXT_0..9_active default (high-active) */

#define CFG_DEFAULT_HOME_MODE 0
#define CFG_DEFAULT_HOME_MOVE_OUT_MM 3.0f
#define CFG_DEFAULT_HOME_SPEED_MM_S 25.0f
#define CFG_DEFAULT_HOME_ACCEL_MM_S2 20.0f

#define CFG_DEFAULT_RAMP_START_HZ 1000
#define CFG_DEFAULT_STOP_APPROACH_HZ 400
#define CFG_DEFAULT_DIR_CHANGE_PAUSE_S 0.1f

/* Path (PC/PD/PG/PN/PS): PATH_BUFFER_MAX is the compile-time static array size
 * (65536 samples * 2 bytes = 128 KB); path_buffer_size is the runtime logical
 * limit (<= PATH_BUFFER_MAX) settable via CS. */
#define PATH_BUFFER_MAX 65536
#define CFG_DEFAULT_PATH_BUFFER_SIZE 64000
#define CFG_DEFAULT_INIT_PATH_SLICE_US 10000
#define PATH_SLICE_US_MIN 1000

#define CFG_LINE_MAX 160
#define CFG_DEFAULT_VERBOSE_RATE_HZ 3
#define CFG_KEY_MAX 32
#define CFG_VAL_MAX 48
